//! Generated by simt-diff/0.1.0. Do not edit.
//!
//! ORACLE: KnownUnsafe, computed by executing every thread of block=32 -- the barrier at barrier@1.0 is reached by 16 of 32 threads of the block, so threads disagree at a block-wide barrier
//!
//! MUTATION: prepend_lane_env_sibling@0.0 of barrier_divergent_intra_warp
//!
//! The prediction for this case, and what it rests on, are in generator.json.

use cuda_device::{DisjointSlice, kernel, launch_contract, thread, warp};


#[kernel]
#[launch_contract(domain = 1, coordinates = u32, block = (32, 1, 1))]
pub fn probe(mut out: DisjointSlice<u32>) {
        let i = thread::index_1d();
        if warp::warp_id() == 0 {
            thread::sync_threads();
        }
        if i.get() % 2 == 0 {
            thread::sync_threads();
        }
        if let Some(e) = out.get_mut(i) { *e = 1; }
}
