//! Turn a case into something a stranger can run (brief §22).
//!
//! A finding is only as good as the smallest thing that demonstrates it. What
//! goes in the directory is therefore not "the case" but the argument: what was
//! expected and on whose authority, what actually happened, the exact commands,
//! and -- the part reproducers usually omit -- what the case does *not* show.
//!
//! `verify.sh` re-runs the analyzer and exits nonzero if the observation has
//! moved. It uses python3 to read the analyzer's own JSON rather than grepping
//! it, because a reproducer that silently passes when the output format changes
//! is worse than one that fails to run.

use std::path::Path;

use crate::classify::DifferentialResult;
use crate::records::{AnalyzerRecord, GeneratorRecord};

/// Everything the package needs to state its case.
pub struct Packaging<'a> {
    pub record: &'a GeneratorRecord,
    pub analysis: &'a AnalyzerRecord,
    pub verdict: &'a DifferentialResult,
    /// One line: what this package is evidence of.
    pub finding: &'a str,
    /// Where the analysis ran, so a difference elsewhere is attributable.
    pub toolchain: String,
}

pub fn write(dir: &Path, p: &Packaging<'_>) -> std::io::Result<()> {
    std::fs::create_dir_all(dir)?;
    crate::emit::emit(
        dir,
        p.record,
        &crate::emit::DeviceDep::default(),
        &crate::emit::DeviceDep::default(),
    )?;
    std::fs::write(dir.join("README.md"), readme(p))?;
    std::fs::write(dir.join("expected.json"), expected(p))?;
    let script = dir.join("verify.sh");
    std::fs::write(&script, VERIFY_SH)?;
    make_executable(&script)?;
    Ok(())
}

#[cfg(unix)]
fn make_executable(path: &Path) -> std::io::Result<()> {
    use std::os::unix::fs::PermissionsExt;
    let mut perms = std::fs::metadata(path)?.permissions();
    perms.set_mode(0o755);
    std::fs::set_permissions(path, perms)
}

#[cfg(not(unix))]
fn make_executable(_path: &Path) -> std::io::Result<()> {
    Ok(())
}

fn expected(p: &Packaging<'_>) -> String {
    let doc = serde_json::json!({
        "schema": "simt-diff.expected.v1",
        "finding": p.finding,
        "signature": p.analysis.signature(),
        "exit_code": p.analysis.exit_code,
        "witnesses": p.analysis.witnesses.len(),
        "analyzer_version": p.analysis.version,
        "toolchain": p.toolchain,
        "oracle": p.record.oracle,
        "oracle_reason": p.record.oracle_reason,
        "expected_static": p.record.expected_static,
        "prediction_basis": p.record.prediction_basis,
        "launches": p.record.launches,
        "kernel_sha256": p.record.kernel_sha256,
    });
    let mut text = serde_json::to_string_pretty(&doc).expect("expected.json serializes");
    text.push('\n');
    text
}

fn readme(p: &Packaging<'_>) -> String {
    let mut t = String::new();
    t.push_str(&format!("# {}\n\n", p.finding));
    t.push_str(&format!(
        "Generated by `{}` from case `{}`.\n\n",
        p.record.generator_version, p.record.template_id
    ));

    t.push_str("## The kernel\n\n```rust\n");
    t.push_str(&p.record.kernel_source);
    t.push_str("```\n\n");

    t.push_str("## What construction knows\n\n");
    t.push_str(&format!(
        "`{:?}` — {}.\n\nThis is not derived from any analyzer output. It is computed \
         by executing every thread of the declared launch.\n\n",
        p.record.oracle, p.record.oracle_reason
    ));

    t.push_str("## What was expected, and on whose authority\n\n");
    t.push_str(&format!("Expected: `{:?}`.\n\n", p.record.expected_static));
    if let Some(basis) = &p.record.prediction_basis {
        t.push_str(&format!("Rule `{}`, provenance **{}**:\n\n> {}\n\n",
            basis.rule,
            basis.provenance.label(),
            basis.provenance.source()
        ));
        match basis.provenance.label() {
            "quoted" => t.push_str(
                "A quoted rule states documented behaviour, so a mismatch is a \
                 statement about the analyzer.\n\n",
            ),
            "extrapolated" => t.push_str(
                "An extrapolated rule was inferred from a documented *reason*, so a \
                 mismatch indicts this laboratory's model first.\n\n",
            ),
            _ => t.push_str(
                "A measured rule was written from an observed run, with the case \
                 named. A mismatch is a regression against that observation.\n\n",
            ),
        }
    }

    t.push_str("## What happened\n\n");
    t.push_str(&format!("Signature: `{}`\n\n", p.analysis.signature()));
    if p.analysis.findings.is_empty() {
        t.push_str("- no findings at any tier\n");
    }
    for f in &p.analysis.findings {
        t.push_str(&format!("- `{}` at `{:?}`: {}\n", f.code, f.confidence, f.message));
        for n in &f.notes {
            t.push_str(&format!("  - {n}\n"));
        }
    }
    t.push_str(&format!(
        "- {} witness artifact(s)\n- exit code {:?}\n\n",
        p.analysis.witnesses.len(),
        p.analysis.exit_code
    ));

    t.push_str("## Reproducing\n\n```sh\n./verify.sh            # exits nonzero if the observation moved\n```\n\n");
    t.push_str("Or by hand, from this directory:\n\n```sh\ncd kernel\ncargo reconverge check --message-format json --strict\nls target/reconverge/witness-*.json 2>/dev/null | wc -l\n```\n\n");
    t.push_str(&format!("Measured with analyzer version `{}`, toolchain `{}`.\n\n", p.analysis.version, p.toolchain));

    t.push_str("## Reading\n\n");
    for line in &p.verdict.interpretation {
        t.push_str(&format!("- {line}\n"));
    }
    t.push_str("\n## What this does not establish\n\n");
    for line in &p.verdict.not_claimed {
        t.push_str(&format!("- {line}\n"));
    }
    t.push_str(
        "- anything about hardware: no GPU was involved in producing this package\n\
         - anything about launches other than the one declared in the contract above\n",
    );
    t
}

const VERIFY_SH: &str = r#"#!/bin/sh
# Re-run the analyzer on this case and compare against expected.json.
#
# Exit 0: the observation is unchanged.
# Exit 1: it moved -- which is the interesting outcome, and why this script
#         parses the analyzer's JSON instead of grepping it.
# Exit 2: the check could not run.
set -eu
cd "$(dirname "$0")"

RECONVERGE="${SIMT_DIFF_RECONVERGE:-cargo-reconverge}"
command -v "$RECONVERGE" >/dev/null 2>&1 || {
    echo "verify: $RECONVERGE not on PATH; set SIMT_DIFF_RECONVERGE" >&2
    exit 2
}
command -v python3 >/dev/null 2>&1 || {
    echo "verify: python3 is required to read the analyzer's JSON" >&2
    exit 2
}

rm -rf kernel/target/reconverge
( cd kernel && "$RECONVERGE" reconverge check --message-format json --strict ) > .verify-out.json 2>.verify-err.txt || true
WITNESSES=$(ls kernel/target/reconverge/witness-*.json 2>/dev/null | wc -l | tr -d ' ')

python3 - "$WITNESSES" <<'PY'
import json, sys

witnesses = int(sys.argv[1])
expected = json.load(open("expected.json"))

found = []
for line in open(".verify-out.json"):
    line = line.strip()
    if not line.startswith("{"):
        continue
    try:
        doc = json.loads(line)
    except ValueError:
        continue
    if doc.get("schema") != "findings.v1":
        continue
    for f in doc.get("findings", []):
        if f.get("code") in ("RC001", "RC002"):
            found.append(f"{f['code']}/{f['confidence']}".lower())

signature = f"{','.join(sorted(found)) or 'silent'}|{witnesses}w"
want = expected["signature"]
print(f"expected: {want}")
print(f"observed: {signature}")
if signature == want:
    print("OK: the observation is unchanged")
    sys.exit(0)
print("MOVED: this case no longer reproduces what it was packaged for", file=sys.stderr)
print("       See README.md for what the expectation rests on.", file=sys.stderr)
sys.exit(1)
PY
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::classify::{Evidence, classify};
    use crate::records::{Confidence, Finding, Launch};

    fn packaging_fixture() -> (GeneratorRecord, AnalyzerRecord) {
        let kernel = crate::mutate::seed("barrier_guarded_by_warp_id").unwrap();
        let record =
            crate::mutate::record_for_kernel(&kernel, "test_case", Launch::one_block(32));
        let analysis = AnalyzerRecord {
            tool: "reconverge".into(),
            version: "0.1.6".into(),
            command: vec!["cargo-reconverge".into()],
            exit_code: Some(0),
            findings: vec![Finding {
                code: "RC001".into(),
                confidence: Confidence::Warning,
                message: "may execute `sync_threads()` under thread-divergent control".into(),
                kernel: Some("probe".into()),
                notes: vec![],
            }],
            raw_stdout: String::new(),
            raw_stderr: String::new(),
            witnesses: vec![],
            crashed: false,
            timed_out: false,
        };
        (record, analysis)
    }

    #[test]
    fn the_package_states_the_provenance_and_what_it_does_not_show() {
        let (record, analysis) = packaging_fixture();
        let verdict = classify(&Evidence {
            generator: &record,
            analyzer: &analysis,
            runs: &[],
            sanitizer: &[],
        });
        let text = readme(&Packaging {
            record: &record,
            analysis: &analysis,
            verdict: &verdict,
            finding: "a lane-environment guard stays at warning tier",
            toolchain: "nightly-2026-04-03".into(),
        });

        assert!(text.contains("## What construction knows"));
        assert!(text.contains("provenance **quoted**"), "the authority is named");
        assert!(text.contains("statement about the analyzer"));
        assert!(text.contains("rc001/warning|0w"), "the signature is stated");
        assert!(
            text.contains("no GPU was involved"),
            "a static-only package must say so"
        );
        assert!(text.contains("nightly-2026-04-03"));
    }

    #[test]
    fn the_expected_document_carries_the_signature_and_the_basis() {
        let (record, analysis) = packaging_fixture();
        let verdict = classify(&Evidence {
            generator: &record,
            analyzer: &analysis,
            runs: &[],
            sanitizer: &[],
        });
        let json: serde_json::Value = serde_json::from_str(&expected(&Packaging {
            record: &record,
            analysis: &analysis,
            verdict: &verdict,
            finding: "f",
            toolchain: "t".into(),
        }))
        .unwrap();
        assert_eq!(json["signature"], "rc001/warning|0w");
        assert_eq!(json["witnesses"], 0);
        assert_eq!(json["oracle"], "KNOWN_SAFE");
        assert!(json["prediction_basis"]["rule"].is_string());
    }

    #[test]
    fn verify_sh_reads_the_json_rather_than_grepping_it() {
        // A reproducer that passes because a grep stopped matching is worse than
        // one that fails to run.
        assert!(VERIFY_SH.contains("json.loads"));
        assert!(VERIFY_SH.contains("findings.v1"));
        assert!(VERIFY_SH.contains("exit 2"), "an unrunnable check is not a pass");
    }
}
