//! Generated by simt-diff/0.1.0. Do not edit.
//!
//! Host runner for case template `barrier_divergent_intra_warp+prepend_lane_env_sibling@0.0`. Prints per-lane values so the
//! differential engine can compare them against the template's reference
//! model; exit code alone is not evidence.

use cuda_core::{CudaContext, DeviceBuffer, LaunchConfig1D};

use cuda_device::{DisjointSlice, cuda_module, kernel, launch_contract, thread, warp};

#[cuda_module]
mod kernels {
    use super::*;
    
    
    
    #[kernel]
    #[launch_contract(domain = 1, coordinates = u32, block = (32, 1, 1))]
    pub fn probe(mut out: DisjointSlice<u32>) {
            let i = thread::index_1d();
            if warp::warp_id() == 0 {
                thread::sync_threads();
            }
            if i.get() % 2 == 0 {
                thread::sync_threads();
            }
            if let Some(e) = out.get_mut(i) { *e = 1; }
    }
}


fn main() {
    let block: u32 = std::env::args()
        .nth(1)
        .and_then(|s| s.parse().ok())
        .unwrap_or(32);
    let n = block as usize;

    let ctx = CudaContext::new(0).expect("cuda context");
    let stream = ctx.default_stream();
    let mut out = DeviceBuffer::<u32>::zeroed(&stream, n).expect("alloc");
    // SAFETY: this package owns the embedded device bundle for `kernels`.
    // `load` is unsafe on current upstream; the `allow` keeps the generated
    // runner compiling against revisions where it is not.
    #[allow(unused_unsafe)]
    let module = unsafe { kernels::load(&ctx) }.expect("load embedded module");

    // A kernel carrying `#[launch_contract]` is launched through the prepared
    // path: the contract is checked against the configuration first, and the
    // typed method then takes the `PreparedLaunch`. Read out of upstream's
    // `coop_groups_demo`, not assumed.
    let config = LaunchConfig1D::new(1, block, 0);
    let prepared = module
        .prepare_probe(config)
        .expect("launch configuration violates the kernel's contract");
    // SAFETY: one block of `block` threads; `out` covers every lane's write.
    unsafe { module.probe(&stream, &prepared, &mut out) }.expect("launch");
    let host = out.to_host_vec(&stream).expect("copy back");

    println!("BLOCK={block}");
    print!("VALUES=");
    for (i, v) in host.iter().enumerate() {
        if i > 0 {
            print!(",");
        }
        print!("{v}");
    }
    println!();
}
